---
name: CI

on: [pull_request]

jobs:

  test:
    name: Unit tests
    strategy:
      matrix:
        python-version: [2.7, 3.6, 3.7]
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
      - name: run tests
        run: python -m pytest --cov=. tests/
      - name: run test coverage
        if: ${{ matrix.python-version == 3.7 }}
        run: |
          coverage report
          coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
